
version: "3"
services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 8000:5432
    networks:
      - network-clicksoft

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - db
    networks:
      - network-clicksoft

networks:
  network-clicksoft:
